# Generated by Django 4.0.6 on 2022-07-17 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('description', models.TextField(max_length=255, null=True)),
                ('unit_price', models.FloatField(max_length=50, null=True)),
                ('base_price', models.FloatField(max_length=50, null=True)),
                ('base_unit', models.CharField(choices=[('packet', 'PACKET'), ('cartoon', 'CARTOON'), ('gallons', 'GALLONS'), ('pounds', 'POUNDS'), ('tons', 'TONS'), ('kilograms', 'KILOGRAMS'), ('gram', 'GRAM'), ('liters', 'LITERS')], default='packet', max_length=20, null=True)),
                ('is_in_stock', models.BooleanField(default=True)),
                ('is_limited', models.BooleanField(default=True)),
            ],
        ),
    ]
