# Generated by Django 4.0.6 on 2022-07-17 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='quantity',
            field=models.IntegerField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='base_unit',
            field=models.CharField(choices=[('packet', 'PACKET'), ('cartoon', 'CARTOON'), ('gallons', 'GALLONS'), ('pounds', 'POUNDS'), ('tons', 'TONS'), ('kilograms', 'KILOGRAMS'), ('gram', 'GRAM'), ('liters', 'LITERS'), ('each', 'EACH')], default='packet', max_length=20, null=True),
        ),
    ]
