# Generated by Django 4.0.5 on 2022-07-18 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_vendors'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Pending', 'PENDING'), ('Out of Stock', 'OUT_OF_STOCK'), ('Delivered', 'DELIVERED'), ('Shipment', 'SHIPMENT')], default='Pending', max_length=20, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Electronic', 'ELECTRONIC'), ('Footwear', 'FOOTWEAR'), ('Consumable', 'CONSUMABLE'), ('Clothing', 'CLOTHING'), ('Industrial', 'INDUSTRIAL')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='base_price',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit_price',
            field=models.FloatField(null=True),
        ),
    ]
