# Generated by Django 4.0.5 on 2022-07-18 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0005_order_product_category_product_date_created_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Vendors',
            new_name='Vendor',
        ),
    ]
